title: AJV Motos
email: contact@ajvmotos.fr
slogan: Pratique de l'Orthodontie à Solliès-Pont
permalink: /:categories/:title.html
description: > # this means to ignore newlines until "baseurl:"
  Mécanique motos, réparation et pièces détachées.
baseurl: "/ajv" # the subpath of your site, e.g. /blog
url: "https://romarr.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


# Gems et extensions
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
exclude:
- Dockerfile

collections_dir: collections

collections:
  actus:
    output: true
    permalink: /actualites/:title
  
sass:
  sass_dir: scss
  style: compressed